# JeloAPI configuration v1

commands:
  # Enable/disable all test commands which its purpose is to do some testing.
  # For production server, we recommend you to disable test commands because it is unnecessary.
  test-commands: true